[[redirects]]
  from = "/"
  to = "/en"
  force = true
  status = 302
  conditions = { Country = ["US", "CA"] }

[template.environment]
  OPTIMIZELY_CMS_URL = "OPTIMIZELY_CMS_URL"
  OPTIMIZELY_GRAPH_SECRET = "OPTIMIZELY_GRAPH_SECRET"
  OPTIMIZELY_GRAPH_APP_KEY = "OPTIMIZELY_GRAPH_APP_KEY"
  OPTIMIZELY_GRAPH_SINGLE_KEY = "OPTIMIZELY_GRAPH_SINGLE_KEY"
